apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: n8n
        image: n8nio/n8n:latest
        ports:
        - containerPort: 5678
        env:
        - name: N8N_PORT
          value: "5678"
        - name: N8N_PROTOCOL
          value: "http"
        - name: NODE_ENV
          value: "production"
        - name: N8N_TELEMETRY_ENABLED
          value: "false"
        volumeMounts:
        - name: n8n-data
          mountPath: /home/node/.n8n
      # TODO: BASIC認証を追加する
      volumes:
      - name: n8n-data
        persistentVolumeClaim:
          claimName: n8n-data # PVCの名前
