# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  namespace: n8n
spec:
  accessModes:
  - ReadWriteMany # 単一Podからの読み書き
  resources:
    requests:
      storage: 32Gi # 必要な容量
  storageClassName: cephfs # 環境に応じて変更
