apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sim-ai
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/infra.git' # Replace with your repository URL
    path: sim.ai/manifests
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sim-ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
