project: default
source:
  repoURL: https://github.com/AobaIwaki123/infra.git
  path: n8n/manifests
  targetRevision: main
destination:
  server: https://kubernetes.default.svc
  namespace: n8n
syncPolicy:
  automated:
    prune: true
    selfHeal: true
    enabled: true
  syncOptions:
  - CreateNamespace=true
