apiVersion: apps/v1
kind: Deployment
metadata:
  name: dify-api
  namespace: dify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dify-api
  template:
    metadata:
      labels:
        app: dify-api
    spec:
      containers:
      - name: api
        image: langgenius/dify-api:1.9.1
        ports:
        - containerPort: 5001
        env:
        - name: MODE
          value: "api"
        envFrom:
        - configMapRef:
            name: dify-config
        - secretRef:
            name: dify-secret
        volumeMounts:
        - name: dify-storage
          mountPath: /app/api/storage
      volumes:
      - name: dify-storage
        persistentVolumeClaim:
          claimName: dify-storage
