resources:
- namespace.yml
- pvc.yml
- postgres-deployment.yml
- postgres-service.yml
- redis-deployment.yml
- redis-service.yml
- api-deployment.yml
- api-service.yml
- worker-deployment.yml
- worker-beat-deployment.yml
- web-deployment.yml
- web-service.yml
- ingress.yml
