apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sim-ai-ingress
  namespace: sim-ai
spec:
  ingressClassName: "cloudflare-tunnel"
  rules:
  - host: sim-ai.aooba.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simstudio
            port:
              number: 3000
  - host: realtime-sim-ai.aooba.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: realtime
            port:
              number: 3002
