apiVersion: batch/v1
kind: Job
metadata:
  name: migrations
  namespace: sim-ai
spec:
  template:
    spec:
      containers:
      - name: migrations
        image: ghcr.io/simstudioai/migrations:latest
        workingDir: /app/packages/db
        command: [ "bun", "run", "db:migrate" ]
        env:
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@db:5432/$(POSTGRES_DB)"
        envFrom:
        - secretRef:
            name: sim-ai-secret
      restartPolicy: Never
  backoffLimit: 4
