apiVersion: apps/v1
kind: Deployment
metadata:
  name: sim-ai-postgres
  namespace: sim-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sim-ai-postgres
  template:
    metadata:
      labels:
        app: sim-ai-postgres
    spec:
      containers:
      - name: postgres
        image: pgvector/pgvector:pg17
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: sim-ai-secret
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: sim-ai-postgres-pvc
